### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by XBeg9** [dlavrenuek/bitnami-mongodb-arm#1]
=> ERROR [ 3/15] RUN install_packages ca-certificates curl libbrotli1 libcom-err2 libcurl4 libffi8 libgcc-s1 libgcrypt20 libgmp10 libgnutls30 libgpg-error0 libgssapi-krb5-2 libhogweed6 libidn  0.1s
------                                                                                                                                                                                                 
 > [ 3/15] RUN install_packages ca-certificates curl libbrotli1 libcom-err2 libcurl4 libffi8 libgcc-s1 libgcrypt20 libgmp10 libgnutls30 libgpg-error0 libgssapi-krb5-2 libhogweed6 libidn2-0 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.5-0 liblzma5 libnettle8 libnghttp2-14 libp11-kit0 libpsl5 librtmp1 libsasl2-2 libssh2-1 libssl3 libtasn1-6 libunistring2 numactl procps zlib1g:
0.083 /bin/bash: line 1: /usr/sbin/install_packages: Permission denied

**Comment by dlavrenuek** [comment]
@XBeg9 how did you download the code, vie git clone or something else? The error indicates that the `install_packages` (located [here](https://github.com/dlavrenuek/bitnami-mongodb-arm/blob/4efad143b5843958fce4cc83fd39a0e07c386c6b/6.0/debian-12/prebuildfs/usr/sbin/install_packages)) script does not have the `x` (execute) flag set, it has the right permission pushed to the repository.

Other information that might help finding the problem: how do you build the image? What hardware are you using?
